/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package net.trainning.dukeclube.visao.gui;

import javax.swing.JFrame;
import net.trainning.dukeclube.visao.ouvinte.OuvinteDeGUISocios;

/**
 *
 * @author trainning
 */
public class GUIPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form GUIPrincipal
     */
    GUISobre guiSobre;
    GUISocios guiSocios;
    public GUIPrincipal() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        menuArquivo = new javax.swing.JMenu();
        itemDeMenuExportarSocios = new javax.swing.JMenuItem();
        itemDeMenuExportartSociosEDependentes = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        itemDeMenuSair = new javax.swing.JMenuItem();
        menuCadastro = new javax.swing.JMenu();
        itemDeMenuCadSocio = new javax.swing.JMenuItem();
        itemDeMenuCadDependente = new javax.swing.JMenuItem();
        menuRelatorio = new javax.swing.JMenu();
        itemDeMenuRelGeral = new javax.swing.JMenuItem();
        menuRelSocio = new javax.swing.JMenu();
        itemDeMenuRelSocioRemido = new javax.swing.JMenuItem();
        itemDeMenuRelSocioBenemerito = new javax.swing.JMenuItem();
        itenDeMenuRelSocioTitular = new javax.swing.JMenuItem();
        menuAjuda = new javax.swing.JMenu();
        itemDeMenuSobre = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("DukeCube");

        menuArquivo.setMnemonic('f');
        menuArquivo.setText("Arquivo");

        itemDeMenuExportarSocios.setMnemonic('o');
        itemDeMenuExportarSocios.setText("Exportar Sócios");
        menuArquivo.add(itemDeMenuExportarSocios);

        itemDeMenuExportartSociosEDependentes.setMnemonic('s');
        itemDeMenuExportartSociosEDependentes.setText("Exportart Sócios/Dependentes");
        menuArquivo.add(itemDeMenuExportartSociosEDependentes);
        menuArquivo.add(jSeparator1);

        itemDeMenuSair.setMnemonic('x');
        itemDeMenuSair.setText("Sair");
        itemDeMenuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemDeMenuSairActionPerformed(evt);
            }
        });
        menuArquivo.add(itemDeMenuSair);

        menuBar.add(menuArquivo);

        menuCadastro.setMnemonic('e');
        menuCadastro.setText("Cadastro");

        itemDeMenuCadSocio.setMnemonic('t');
        itemDeMenuCadSocio.setText("Sócio");
        itemDeMenuCadSocio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemDeMenuCadSocioActionPerformed(evt);
            }
        });
        menuCadastro.add(itemDeMenuCadSocio);

        itemDeMenuCadDependente.setMnemonic('y');
        itemDeMenuCadDependente.setText("Dependente");
        menuCadastro.add(itemDeMenuCadDependente);

        menuBar.add(menuCadastro);

        menuRelatorio.setText("Relatório");

        itemDeMenuRelGeral.setText("Geral");
        menuRelatorio.add(itemDeMenuRelGeral);

        menuRelSocio.setText("Sócio");

        itemDeMenuRelSocioRemido.setText("Remido");
        menuRelSocio.add(itemDeMenuRelSocioRemido);

        itemDeMenuRelSocioBenemerito.setText("Benemérito");
        menuRelSocio.add(itemDeMenuRelSocioBenemerito);

        itenDeMenuRelSocioTitular.setText("Titular");
        menuRelSocio.add(itenDeMenuRelSocioTitular);

        menuRelatorio.add(menuRelSocio);

        menuBar.add(menuRelatorio);

        menuAjuda.setMnemonic('h');
        menuAjuda.setText("Ajuda");

        itemDeMenuSobre.setMnemonic('a');
        itemDeMenuSobre.setText("Sobre o DukeClube");
        itemDeMenuSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemDeMenuSobreActionPerformed(evt);
            }
        });
        menuAjuda.add(itemDeMenuSobre);

        menuBar.add(menuAjuda);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemDeMenuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemDeMenuSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_itemDeMenuSairActionPerformed

    private void itemDeMenuSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemDeMenuSobreActionPerformed
        // TODO add your handling code here:
        if(guiSobre == null){
            guiSobre = new GUISobre();
            desktopPane.add(guiSobre);
            guiSobre.setVisible(true);
            guiSobre.setPosition();
        }
    }//GEN-LAST:event_itemDeMenuSobreActionPerformed

    private void itemDeMenuCadSocioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemDeMenuCadSocioActionPerformed
        if(guiSocios == null){
            guiSocios = new GUISocios();
            OuvinteDeGUISocios ouvinte = new OuvinteDeGUISocios(guiSocios);
        }
        desktopPane.add(guiSocios);
        guiSocios.setVisible(true);
        guiSocios.setPosicao();
    }//GEN-LAST:event_itemDeMenuCadSocioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new GUIPrincipal().setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem itemDeMenuCadDependente;
    private javax.swing.JMenuItem itemDeMenuCadSocio;
    private javax.swing.JMenuItem itemDeMenuExportarSocios;
    private javax.swing.JMenuItem itemDeMenuExportartSociosEDependentes;
    private javax.swing.JMenuItem itemDeMenuRelGeral;
    private javax.swing.JMenuItem itemDeMenuRelSocioBenemerito;
    private javax.swing.JMenuItem itemDeMenuRelSocioRemido;
    private javax.swing.JMenuItem itemDeMenuSair;
    private javax.swing.JMenuItem itemDeMenuSobre;
    private javax.swing.JMenuItem itenDeMenuRelSocioTitular;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenu menuAjuda;
    private javax.swing.JMenu menuArquivo;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuCadastro;
    private javax.swing.JMenu menuRelSocio;
    private javax.swing.JMenu menuRelatorio;
    // End of variables declaration//GEN-END:variables

}
