/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package net.trainning.dukeclube.visao.gui;

import java.awt.Dimension;

/**
 *
 * @author trainning
 */
public class GUISobre extends javax.swing.JInternalFrame {

    /**
     * Creates new form GUISobre
     */
    public GUISobre() {
        initComponents();
    }

    public void setPosition()
    {
        Dimension d = this.getDesktopPane().getSize();
        this.setLocation((d.width - this.getSize().width)/2,
                         (d.height - this.getSize().height)/2);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lNomeDoAplicativo = new javax.swing.JLabel();
        lVersaoDoAplicativo = new javax.swing.JLabel();
        lAutorDoAplicativo = new javax.swing.JLabel();
        lDescricaoDoAplicativo = new javax.swing.JLabel();
        lLicencaDoAplicativo = new javax.swing.JLabel();
        tfAutor = new javax.swing.JTextField();
        bFechar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        taLicenca = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        taDescricao = new javax.swing.JTextArea();

        setClosable(true);
        setTitle("DukeClube - Sobre");

        lNomeDoAplicativo.setText("DukeClube");

        lVersaoDoAplicativo.setText("Versão 1.0");

        lAutorDoAplicativo.setText("Autor ");

        lDescricaoDoAplicativo.setText("Descrição");

        lLicencaDoAplicativo.setText("Licença");

        tfAutor.setEditable(false);
        tfAutor.setText("Francisco Souza");

        bFechar.setText("Fechar");
        bFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bFecharActionPerformed(evt);
            }
        });

        taLicenca.setEditable(false);
        taLicenca.setColumns(20);
        taLicenca.setLineWrap(true);
        taLicenca.setRows(5);
        taLicenca.setText("Licença Pública da GNU (GNU General Public License), conforme publicada pela Free Software Foundation");
        taLicenca.setWrapStyleWord(true);
        jScrollPane1.setViewportView(taLicenca);

        taDescricao.setEditable(false);
        taDescricao.setColumns(20);
        taDescricao.setLineWrap(true);
        taDescricao.setRows(5);
        taDescricao.setText("Aplicativo-exemplo implementado passo a passo ao longo do curso com o propósito de demonstrar a utilização de padrões de projeto na construção de softwares orientados a objetos.");
        taDescricao.setWrapStyleWord(true);
        jScrollPane2.setViewportView(taDescricao);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bFechar)
                .addGap(175, 175, 175))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lNomeDoAplicativo)
                    .addComponent(lVersaoDoAplicativo)
                    .addComponent(lAutorDoAplicativo)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lDescricaoDoAplicativo)
                            .addComponent(lLicencaDoAplicativo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE)
                            .addComponent(tfAutor)
                            .addComponent(jScrollPane2))))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lNomeDoAplicativo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lVersaoDoAplicativo)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lAutorDoAplicativo)
                    .addComponent(tfAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lDescricaoDoAplicativo)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lLicencaDoAplicativo)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bFechar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void bFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bFecharActionPerformed
    // TODO add your handling code here:
        this.dispose();        
    }//GEN-LAST:event_bFecharActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bFechar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lAutorDoAplicativo;
    private javax.swing.JLabel lDescricaoDoAplicativo;
    private javax.swing.JLabel lLicencaDoAplicativo;
    private javax.swing.JLabel lNomeDoAplicativo;
    private javax.swing.JLabel lVersaoDoAplicativo;
    private javax.swing.JTextArea taDescricao;
    private javax.swing.JTextArea taLicenca;
    private javax.swing.JTextField tfAutor;
    // End of variables declaration//GEN-END:variables
}
